apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.name}}-webpdf
type: Opaque
data:
  user: "{{ .Values.callback.smtp.user | b64enc }}"
  password: "{{ .Values.callback.smtp.password | b64enc }}"